export enum LANGUAGE {
  RUS = "RUS",
}

export enum AUTH {
  LOGIN = "LOGIN",
  FORGOTPASS = "FORGOTPASS",
  REGISTER = "REGISTER",
  TABS = "TABS"
}

export enum STACk {
  HOME_STACK = "HOME_STACK",
  PROFILE_STACK = "HOME_STACK",
  LIKED_STACK = "LIKED_STACK",
  BALANCE_STACK = "BALANCE_STACK"
}

export enum HOME {
  HOME = "HOME",
  CATEGORY = "CATEGORY",
  COURSE = "COURSE",
  FILTER = "FILTER",
  NOTIFICATION = 'NOTIFICATION',
  ENGLISHWITH = "ENGLISHWITH",
  BUYCOURSE = "BUYCOURSE",
  ALLREVIEWS = "ALLREVIEWS"
}

export enum PROFILE {
  PROFILE = "PROFILE",
  CHANGEPROFILE = "CHANGEPROFILE"
}

export enum LIKED {
  LIKED = "LIKED"
}

export enum BALANCE {
  BALANCE = "BALANCE",
  TRANSACTIONS = "TRANSACTIONS",
  MYREVIEWS = "MYREVIEWS"
}

export enum DRAWER {
  HOME = "HOME",
  PROFILE = "PROFILE",
  LIKED = "LIKED",
  BALANCE = "BALANCE"
}



export const ROUTES = {
  LANGUAGE,
  AUTH,
  HOME,
  PROFILE,
  STACk,
  BALANCE,
  LIKED,
  DRAWER
} as const;
